In [2]:
import pandas as pd

In [4]:
data_raw = pd.read_csv('../data/etuovi_raw.csv')

In [6]:
data_raw[['Type','Raw_2']] = data_raw.Raw_Data.str.split("|",expand=True, n=1)
data_raw[["Raw_3", "Year"]] = data_raw.Raw_2.str.split("Vuosi", expand=True, n=1)
data_raw['Year_Built'] = data_raw['Year'].str[:4]
data_raw[["Raw_4", "Price_Iteration"]] = data_raw.Raw_3.str.split("Hinta", expand=True, n=1)
data_raw[["Price", "Size"]] = data_raw.Price_Iteration.str.split("Koko", expand=True, n=1)
data_raw["Size_m²"] = data_raw["Size"].str.replace(" m²","")
data_raw['Price_euro'] = data_raw['Price'].str.replace('€',"")

data_raw

,Raw_Data,Type,Raw_2,Raw_3,Year,Year_Built,Raw_4,Price_Iteration,Price,Size,Size_m²,Price_euro
0,Kerrostalo | 1h + k + alk + et + kphAntinkatu ...,Kerrostalo,"1h + k + alk + et + kphAntinkatu 33 A, Riihik...","1h + k + alk + et + kphAntinkatu 33 A, Riihik...",1938Uusi 24H,1938,"1h + k + alk + et + kphAntinkatu 33 A, Riihik...","85 000 €Koko48,9 m²",85 000 €,"48,9 m²","48,9",85 000
1,"KerrostaloJ. Vilmsi tn, Kadriorg, Tallinn Viro...","KerrostaloJ. Vilmsi tn, Kadriorg, Tallinn Viro...",None,None,None,None,None,None,None,None,None,None
2,"KerrostaloF. R. Kreutzwaldi tn, Kadriorg, Tall...","KerrostaloF. R. Kreutzwaldi tn, Kadriorg, Tall...",None,None,None,None,None,None,None,None,None,None
3,"Kerrostalo | 1h + kphRuukinkuja 2, Hiironen, O...",Kerrostalo,"1h + kphRuukinkuja 2, Hiironen, OuluHinta99 8...","1h + kphRuukinkuja 2, Hiironen, OuluHinta99 8...",2017Uusi 24H,2017,"1h + kphRuukinkuja 2, Hiironen, Oulu","99 800 €Koko27,5 m²",99 800 €,"27,5 m²","27,5",99 800
4,"Kerrostalo | 2 h, ktAsentajakuja 2 A 8, Mutala...",Kerrostalo,"2 h, ktAsentajakuja 2 A 8, Mutala, JoensuuHin...","2 h, ktAsentajakuja 2 A 8, Mutala, JoensuuHin...",2022Uusi 24H,2022,"2 h, ktAsentajakuja 2 A 8, Mutala, Joensuu",137 000 €Koko36 m²,137 000 €,36 m²,36,137 000
...,...,...,...,...,...,...,...,...,...,...,...,...
32992,Erillistalo | 6h + k + 2wc + s + kph / 2h + kL...,Erillistalo,6h + k + 2wc + s + kph / 2h + kLiimattalantie...,6h + k + 2wc + s + kph / 2h + kLiimattalantie...,1951Yksityinen myyjä,1951,6h + k + 2wc + s + kph / 2h + kLiimattalantie...,185 000 €Koko260 / 350 m²,185 000 €,260 / 350 m²,260 / 350,185 000
32993,"Erillistalo | HallirakennusUkkolantie 3, Käpyk...",Erillistalo,"HallirakennusUkkolantie 3, Käpykangas, Joensu...","HallirakennusUkkolantie 3, Käpykangas, Joensu...",1973,1973,"HallirakennusUkkolantie 3, Käpykangas, Joensuu",180 000 €Koko316 m²,180 000 €,316 m²,316,180 000
32994,"Erillistalo | 5h + avok + s, 2wc.Purolaakso 4 ...",Erillistalo,"5h + avok + s, 2wc.Purolaakso 4 C, Askisto, V...","5h + avok + s, 2wc.Purolaakso 4 C, Askisto, V...",1986Yksityinen myyjä,1986,"5h + avok + s, 2wc.Purolaakso 4 C, Askisto, V...",335 000 €Koko150 m²,335 000 €,150 m²,150,335 000
32995,"Erillistalo | 3h + k, 2 WCVanhatie 24, Kirkonk...",Erillistalo,"3h + k, 2 WCVanhatie 24, Kirkonkylä, Pomarkku...","3h + k, 2 WCVanhatie 24, Kirkonkylä, Pomarkku...",2000Hintamuutos,2000,"3h + k, 2 WCVanhatie 24, Kirkonkylä, Pomarkku",101 000 €128 000 €Koko103 m²,101 000 €128 000 €,103 m²,103,101 000 128 000
32996,"Erillistalo | 5h + k, sauna ja 2h + k parveke...",Erillistalo,"5h + k, sauna ja 2h + k parveke, + työtila j...","5h + k, sauna ja 2h + k parveke, + työtila j...",1991Yksityinen myyjä,1991,"5h + k, sauna ja 2h + k parveke, + työtila j...",268 000 €Koko245 / 425 m²,268 000 €,245 / 425 m²,245 / 425,268 000