In [41]:
import numpy as np
import pandas as pd

In [42]:
df = pd.read_csv('014_112p_2021q2_20210920-161913.csv', encoding="unicode_escape",sep='\t', skiprows=1)
df

,Postal code,Building type,2010Q1 Price per square meter (EUR/m2),2010Q2 Price per square meter (EUR/m2),2010Q3 Price per square meter (EUR/m2),2010Q4 Price per square meter (EUR/m2),2011Q1 Price per square meter (EUR/m2),2011Q2 Price per square meter (EUR/m2),2011Q3 Price per square meter (EUR/m2),2011Q4 Price per square meter (EUR/m2),...,2019Q1 Price per square meter (EUR/m2),2019Q2 Price per square meter (EUR/m2),2019Q3 Price per square meter (EUR/m2),2019Q4 Price per square meter (EUR/m2),2020Q1 Price per square meter (EUR/m2),2020Q2 Price per square meter (EUR/m2),2020Q3 Price per square meter (EUR/m2),2020Q4 Price per square meter (EUR/m2),2021Q1* Price per square meter (EUR/m2),2021Q2* Price per square meter (EUR/m2)
0,00100 Helsinki Keskusta - Etu-Töölö (Helsinki ),"Blocks of flats, one-room flat",5458,5347,5826,5566,5545,5812,5909,5856,...,7755,8332,8130,8068,7802,8543,9170,7517,8872,8596
1,00100 Helsinki Keskusta - Etu-Töölö (Helsinki ),"Blocks of flats, two-room flat",5164,5021,5081,5006,5713,5866,5552,5614,...,6914,7694,6901,7435,7573,7398,7868,7700,7829,7974
2,00100 Helsinki Keskusta - Etu-Töölö (Helsinki ),"Blocks of flats, three-room flat+",4944,5396,4828,5394,5571,5709,5450,5010,...,6883,6846,7379,6728,7205,6678,7178,7405,8053,8174
3,00100 Helsinki Keskusta - Etu-Töölö (Helsinki ),Blocks of flats total,5168,5219,5181,5269,5632,5807,5630,5511,...,7043,7478,7476,7345,7460,7275,8058,7540,8188,8188
4,00100 Helsinki Keskusta - Etu-Töölö (Helsinki ),Terraced houses total,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10069,99980 Utsjoki Keskus (Utsjoki ),"Blocks of flats, two-room flat",..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
10070,99980 Utsjoki Keskus (Utsjoki ),"Blocks of flats, three-room flat+",..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
10071,99980 Utsjoki Keskus (Utsjoki ),Blocks of flats total,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
10072,99980 Utsjoki Keskus (Utsjoki ),Terraced houses total,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
10073,99980 Utsjoki Keskus (Utsjoki ),Building types total,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [43]:
df.columns

Index(['Postal code', 'Building type',
       '2010Q1 Price per square meter (EUR/m2)',
       '2010Q2 Price per square meter (EUR/m2)',
       '2010Q3 Price per square meter (EUR/m2)',
       '2010Q4 Price per square meter (EUR/m2)',
       '2011Q1 Price per square meter (EUR/m2)',
       '2011Q2 Price per square meter (EUR/m2)',
       '2011Q3 Price per square meter (EUR/m2)',
       '2011Q4 Price per square meter (EUR/m2)',
       '2012Q1 Price per square meter (EUR/m2)',
       '2012Q2 Price per square meter (EUR/m2)',
       '2012Q3 Price per square meter (EUR/m2)',
       '2012Q4 Price per square meter (EUR/m2)',
       '2013Q1 Price per square meter (EUR/m2)',
       '2013Q2 Price per square meter (EUR/m2)',
       '2013Q3 Price per square meter (EUR/m2)',
       '2013Q4 Price per square meter (EUR/m2)',
       '2014Q1 Price per square meter (EUR/m2)',
       '2014Q2 Price per square meter (EUR/m2)',
       '2014Q3 Price per square meter (EUR/m2)',
       '2014Q4 Price per square meter (EUR/m2)',
       '2015Q1 Price per square meter (EUR/m2)',
       '2015Q2 Price per square meter (EUR/m2)',
       '2015Q3 Price per square meter (EUR/m2)',
       '2015Q4 Price per square meter (EUR/m2)',
       '2016Q1 Price per square meter (EUR/m2)',
       '2016Q2 Price per square meter (EUR/m2)',
       '2016Q3 Price per square meter (EUR/m2)',
       '2016Q4 Price per square meter (EUR/m2)',
       '2017Q1 Price per square meter (EUR/m2)',
       '2017Q2 Price per square meter (EUR/m2)',
       '2017Q3 Price per square meter (EUR/m2)',
       '2017Q4 Price per square meter (EUR/m2)',
       '2018Q1 Price per square meter (EUR/m2)',
       '2018Q2 Price per square meter (EUR/m2)',
       '2018Q3 Price per square meter (EUR/m2)',
       '2018Q4 Price per square meter (EUR/m2)',
       '2019Q1 Price per square meter (EUR/m2)',
       '2019Q2 Price per square meter (EUR/m2)',
       '2019Q3 Price per square meter (EUR/m2)',
       '2019Q4 Price per square meter (EUR/m2)',
       '2020Q1 Price per square meter (EUR/m2)',
       '2020Q2 Price per square meter (EUR/m2)',
       '2020Q3 Price per square meter (EUR/m2)',
       '2020Q4 Price per square meter (EUR/m2)',
       '2021Q1* Price per square meter (EUR/m2)',
       '2021Q2* Price per square meter (EUR/m2)'],
      dtype='object')

In [45]:
df['Postal Code'] = df['Postal code'].map(lambda x: x[0:5])
df['Location'] = df['Postal code'].map(lambda x: x[5:])
df.drop(columns = ['Postal code'],inplace=True)

KeyError: 'Postal code'

In [46]:
df.sample(5)

,Building type,2010Q1 Price per square meter (EUR/m2),2010Q2 Price per square meter (EUR/m2),2010Q3 Price per square meter (EUR/m2),2010Q4 Price per square meter (EUR/m2),2011Q1 Price per square meter (EUR/m2),2011Q2 Price per square meter (EUR/m2),2011Q3 Price per square meter (EUR/m2),2011Q4 Price per square meter (EUR/m2),2012Q1 Price per square meter (EUR/m2),...,2019Q3 Price per square meter (EUR/m2),2019Q4 Price per square meter (EUR/m2),2020Q1 Price per square meter (EUR/m2),2020Q2 Price per square meter (EUR/m2),2020Q3 Price per square meter (EUR/m2),2020Q4 Price per square meter (EUR/m2),2021Q1* Price per square meter (EUR/m2),2021Q2* Price per square meter (EUR/m2),Postal Code,Location
4023,Blocks of flats total,..,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,32500,Oripää Keskus (Oripää )
861,Blocks of flats total,2616,2691,2588,2867,2633,2844,2944,2805,2878,...,3182,2958,3060,3268,2999,3173,3061,3277,02320,Espoonlahti (Espoo )
1099,"Blocks of flats, two-room flat",..,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,02880,Veikkola (Kirkkonummi )
4287,Blocks of flats total,..,..,1576,..,..,..,1472,..,..,...,..,..,..,..,..,..,1572,..,33840,Peltolammi (Tampere )
4928,"Blocks of flats, three-room flat+",..,..,..,..,..,..,..,..,..,...,1702,1690,1430,1539,..,1640,1661,1528,40320,Seppälän Teollisuusalue (Jyväskylä )

AttributeError: 'DataFrameGroupBy' object has no attribute 'groupby'